# Generated by Django 5.0.3 on 2024-03-17 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0002_empresa_inmueble_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='inmuebleslist_app.empresa'),
            preserve_default=False,
        ),
    ]
