# Generated by Django 5.0.3 on 2024-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_comentario_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='number_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
